import { faUtensils, faShoppingBag, faPaintBrush, faFutbol, faCamera, faCoffee, faBuilding, faCut, faHome, faUtensilSpoon, faMedkit, faBuildingUser, faGraduationCap, faLeaf, faMugHot, faDumbbell, faUserTie, faHotel, faNewspaper } from "@fortawesome/free-solid-svg-icons";
export const categories = [
    { title: "Restaurants", icon: faUtensils },
    { title: "Shopping", icon: faShoppingBag },
    { title: "Art & Craft", icon: faPaintBrush },
    { title: "Sports", icon: faFutbol },
    { title: "Photo Studios", icon: faCamera },
    { title: "Cafes", icon: faCoffee },
    { title: "Car Showrooms", icon: faBuilding },
    { title: "Beauty & Saloon", icon: faCut },
    { title: "Home Services", icon: faHome },
    { title: "Food", icon: faUtensilSpoon },
    { title: "Health & Medical", icon: faMedkit },
    { title: "Real Estate", icon: faBuildingUser },
    { title: "Education", icon: faGraduationCap },
    { title: "Local Flavour", icon: faLeaf },
    { title: "Coffee & Tea", icon: faMugHot },
    { title: "Gym", icon: faDumbbell },
    { title: "Professional Services", icon: faUserTie },
    { title: "Hotel & Travel", icon: faHotel },
    { title: "Media", icon: faNewspaper },
  ];